export default {
	GET_WEATHER_PENDING: 'GET_WEATHER_PENDING',
	GET_WEATHER_FULFILLED: 'GET_WEATHER_FULFILLED',
	GET_WEATHER_REJECTED: 'GET_WEATHER_REJECTED',
	GET_INFO_LAT_LNG_PENDING: 'GET_INFO_LAT_LNG_PENDING',
	GET_INFO_LAT_LNG_FULFILLED: 'GET_INFO_LAT_LNG_FULFILLED',
	GET_INFO_LAT_LNG_REJECTED: 'GET_INFO_LAT_LNG_REJECTED'
};